[package]
name = "term-box"
version = "0.1.0"
edition = "2024"

[lib]
test = true
doctest = true
crate-type = ["lib"]

[dependencies]
ansi-width = "0.1.0"
nu-ansi-term = "0.50.1"

[dev-dependencies]
derive-new = "0.7.0"
